### ISSUE TITLE
How to use External .tga and .dds for models?

### ISSUE THREAD

**Issue by RustOsprey55681** [ollerjoaco/Trinity-EngineSv#11]
I knew how to do it to the World texture but not for the Models.
any help??

**Comment by ollerjoaco** [comment]
This is the way it works:

1. You have a model and imagine you opened it with HLMV
2. You get the textures names for the model ( you can now just close HLMV you are not going to use it more than for getting textures names )
3. You get a higher resoultion texture for those textures you want to replace
4. You go to cstrike\gfx\textures\models and create a folder with your guns name ie v_ak47
5. They can be either a .tga or .dds ( I recommend the last one as it has a better compression but both work fine )
6. Finally you add a line to the cstrike\gfx\textures\texture-flags.txt that need to be something like this
v_ak47   74_body_diff   alternate
v_ak47   v_hands   alternate

With one space only I just added more for you to see it better
GunModel   TextureName   alternate

Alternate is a parameter that will change the texture not as a _detail makes it that just put it above the old one, instead, this replaces the texture completely so it will look better.

Please let me know if you have any problem.

**Comment by RustOsprey55681** [comment]
Sorry for the late response, But thanks for replying. I'll try that soon.

**Comment by RustOsprey55681** [comment]
Ok now, I have another **_question_**. Is it possible to set external textures for multiple models without making multiple text files?
Like, for **example**: Changing the **v_hands** texture for all weapons ViewModel.
Like how **[THIS](https://csumods.blogspot.com/2023/08/cs16-plugin-metahook-mhstudiotga.html)** plugin works.

**Comment by ollerjoaco** [comment]
Sorry but I´m unsure about it and Im not working on this anymore. You can read all the documentation in the [readme](https://github.com/ollerjoaco/Trinity-EngineSv/tree/main/readme) section of this repository. I think its not possible but with a small change in the code it should probably work fine. At the moment I think the only way is making multiple text files.

**Comment by RustOsprey55681** [comment]
Ok, that will be not a big problem, I think. Thank you for helping me anyway.
